# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{king_dtaus}
  s.version = "1.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Georg Leciejewski", "Georg Ledermann"]
  s.date = %q{2010-09-14}
  s.description = %q{DTAUS is a text-based format, to create bank transfers for german banks. This gem helps with the creation of those transfer files.}
  s.email = %q{gl@salesking.eu}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    ".gitignore",
     "MIT-LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/king_dta/account.rb",
     "lib/king_dta/booking.rb",
     "lib/king_dta/dtaus.rb",
     "lib/king_dta/helper.rb",
     "lib/king_dtaus.rb",
     "spec/booking_spec.rb",
     "spec/dtaus_spec.rb",
     "spec/helper_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/salesking/king_dtaus}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Generate DTAUS strings and files}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/booking_spec.rb",
     "spec/helper_spec.rb",
     "spec/dtaus_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

